server:
  port: 8083

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-location: file:///Users/Vladislav/IdeaProjects/spring cloud demo/config-service/config-service/src/main/resources/config
